### ISSUE TITLE
Error while install

### ISSUE THREAD

**Issue by ChristopheSilva** [Mrcuve0/Aritim-Dark#1] opened 2019-05-16 19:17 UTC
Hi there, i'm having an error while tying to instal:

sudo kpackagetool5 -i Aritim-Dark-KDE-master.zip 
couldn't find knsrc file for "wallpaper.knsrc"
Empty filename passed to function
Erro: A instalação de /home/christoph3/Transferências/Aritim-Dark-KDE-master.zip foi mal-sucedida: Não foi possível instalar a dependência: 'kns://wallpaper.knsrc/api.kde-look.org/1291306'

**Comment by Mrcuve0** [comment] 2019-05-23 10:41
Hi, thanks for reporting this issue.
That's quite strange: I tried to reproduce the issue on a VM using KDE Neon and this is the log I got:
```
sudo kpackagetool5 -i Aritim-Dark-KDE-master.zip
```

```
installing...
org.kde.knewstuff.core: Could not determine type of archive file ' "/tmp/vBysZe-Aritim-Dark-Wallpaper-1920x1080.jpg" '
installing...
QProcess: Destroyed while process ("/usr/lib/x86_64-linux-gnu/libexec/kf5/kpackagehandlers/knshandler") is still running.
installing...
org.kde.knewstuff.core: Could not determine type of archive file ' "/tmp/fQLPnn-AritimDark.colors" '
installing...
installing...
Successfully installed /home/neon/Downloads/Aritim-Dark-KDE-master.zip
```

Despite the displayed errors, I still obtain a successful installation: the theme is correctly installed such as as the color palette and the wallpaper (which is not set automatically, I still have to figure this out...)

I don't know actually why you are having this problem, I'll wait to have new feedback.

The best and user-friendly way to install a KDE theme is by going on *Settings* --> "Workspace theme* --> *Look and feel* --> *Get new Look and Feel Themes* and finally select the theme you are looking for (downloaded and installed automatically from the KDE Store).

![Screenshot_20190523_124102](https://user-images.githubusercontent.com/36898760/58246713-14bc7580-7d58-11e9-9fc2-1c4f30967a9b.png)

**Comment by ChristopheSilva** [comment] 2019-05-23 14:15
Hi there, tried to install using terminal way and graphical way without success. When I tried to install via " get new themes for plasma" it install but does not show in the available installed themes. Via terminal it gives the error reported in kde neon and also in a fresh arch+plasma install. Best regards

**Comment by Mrcuve0** [comment] 2019-05-23 15:17
So I tried to look for it on the Internet. What I found so far: 
* [Here](https://forum.kde.org/viewtopic.php?t=138995) (A very similar dependency problem on Arch and Neon).
* Here's just my guessing: try to find if under `/etc/xdg/` you can find the `wallpaper.knsrc`. Let me know if there's one in your system.

As suggested by the first link, this could be probably linked to a dependency you don't have on both your systems (although it seems strange since my clean live-usb of KDE Neon works so far but not yours).

Finally, since this seems really a though problem to debug, try to modify the `metadata.desktop` file contained into the theme's zipped folder. This file contains all the dependencies that are downloaded automatically during installation.
It's just a matter of deleting this string and relaunch the installation (you can repeat this with all the dependencies that may cause problems): 
![Screenshot_20190523_171409](https://user-images.githubusercontent.com/36898760/58264476-39c3df00-7d7e-11e9-9597-7a4a6d2d9d99.png)

Finally, if the installation completes successfully, you can download manually the wallpaper if you want: https://store.kde.org/p/1291306

**Comment by ChristopheSilva** [comment] 2019-05-23 16:41
Hi there, tried it again in kde neon fresh install and also on my main arch+plasma no luck, if i install via graphic it does not show aritim theme on available themes.

**Comment by Mrcuve0** [comment] 2019-05-23 19:09
> if i install via graphic it does not show aritim theme on available themes.

That's really strange.
I found this thread on the opendesktop community: 
* https://forum.opendesktop.org/t/problem-with-downloading-look-and-feel-themes/17689
* https://www.reddit.com/r/kde/comments/bp2r8h/cant_install_look_and_feel_themes/?utm_medium=android_app&utm_source=share

This is probably the problem you are encountering. Try to reproduce the commands that you can find on the reddit thread (the second link) (`kcmshell5 kcm_lookandfeel`) and follow the instructions on the same thread.

This will probably explain why both Kde Neon and Arch are affected but not my Manjaro I'm currently writing from: both the distros come with the most updated packages so these kind of problem have a higher probability to happen.
Finally, my KDE Neon ISO that I used on my VM is dated 2018 so it has outdated packages, that's why I didn't face the problem.

Let me know, we may have found a solution!

**Comment by Mrcuve0** [comment] 2019-05-30 20:32
No feedback received so far. Assuming the problem was solved and closing the issue.

**Closed as completed by Mrcuve0** 2019-05-30 20:32 UTC
